<?php

/**
 * @file
 * An implementation of integration between RNG and Commerce.
 */

use Drupal\commerce_order\Entity\OrderInterface;
use Drupal\commerce_order\Entity\OrderItemInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\profile\Entity\ProfileInterface;
use Drupal\rng\Entity\RegistrantInterface;
use Drupal\rng\Entity\RegistrationInterface;

/*******************************************************************************
 * DRUPAL HOOKS
 ******************************************************************************/

/**
 * Implements hook_entity_extra_field_info().
 */
function commerce_rng_entity_extra_field_info() {
  $extra = [];

  $extra['registrant']['registrant']['display']['registration'] = [
    'label' => t('Registration'),
    'description' => t('Link to the registration entity.'),
    'visible' => FALSE,
  ];
  $extra['registrant']['registrant']['display']['order'] = [
    'label' => t('Order', [], ['context' => 'commerce_order']),
    'description' => t('Link to the order that this registrant belongs to.'),
    'visible' => FALSE,
  ];
  $extra['registrant']['registrant']['display']['event'] = [
    'label' => t('Event'),
    'description' => t('Link to the event.'),
    'visible' => FALSE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view() for registrant entities.
 */
function commerce_rng_registrant_view(array &$build, EntityInterface $registrant, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('registration')) {
    $registration = $registrant->getRegistration();
    if ($registration->access('view')) {
      $build['registration'] = $registration->toLink(t('Registration'))->toRenderable();
    }
  }

  if ($display->getComponent('order')) {
    $registration = $registrant->getRegistration();
    $order_item = \Drupal::service('commerce_rng.registration_data')
      ->registrationGetOrderItem($registration);
    if ($order_item instanceof OrderItemInterface) {
      $order = $order_item->getOrder();

      if ($order->access('view')) {
        $build['order'] = [
          '#type' => 'item',
          '#title' => t('Order', [], ['context' => 'commerce_order']),
          $order->toLink()->toRenderable(),
        ];
      }
    }
  }

  if ($display->getComponent('event')) {
    $event = $registrant->getRegistration()
      ->getEvent();

    if ($event instanceof EntityInterface && $event->access('view')) {
      $build['event'] = [
        '#type' => 'item',
        '#title' => t('Event'),
        $event->toLink()->toRenderable(),
      ];
    }
  }
}

/*******************************************************************************
 * ENTITY HOOKS
 ******************************************************************************/

/**
 * Implements hook_ENTITY_TYPE_presave() for entity type 'commerce_order_item'.
 */
function commerce_rng_commerce_order_item_presave(OrderItemInterface $order_item) {
  // Update the order item's quantity.
  \Drupal::service('commerce_rng.registration_data')->orderItemUpdateQuantity($order_item);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for entity type 'commerce_order_item'.
 */
function commerce_rng_commerce_order_item_delete(OrderItemInterface $order_item) {
  // Cleanup registration when order item gets deleted.
  $registration = \Drupal::service('commerce_rng.registration_data')->getRegistrationByOrderItemId($order_item->id());
  if ($registration instanceof RegistrationInterface) {
    $registration->delete();
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for entity type 'registrant'.
 */
function commerce_rng_registrant_insert(RegistrantInterface $registrant) {
  $registration = $registrant->getRegistration();
  if (!$registration) {
    return;
  }

  $order_item = \Drupal::service('commerce_rng.registration_data')->registrationGetOrderItem($registration);
  if (!$order_item) {
    return;
  }

  // Update the order item.
  $order_item->save();
}

/**
 * Implements hook_ENTITY_TYPE_update() for entity type 'registrant'.
 */
function commerce_rng_registrant_update(RegistrantInterface $registrant) {
  // Do the same as when inserting a registrant.
  commerce_rng_registrant_insert($registrant);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for entity type 'registrant'.
 */
function commerce_rng_registrant_delete(RegistrantInterface $registrant) {
  // Do the same as when inserting a registrant.
  commerce_rng_registrant_insert($registrant);
}

/*******************************************************************************
 * COMMERCE RNG HOOKS
 ******************************************************************************/

/**
 * Implements hook_commerce_rng_persons_list_alter().
 */
function commerce_rng_commerce_rng_persons_list_alter(array &$persons, OrderInterface $order, RegistrationInterface $registration) {
  // If the list of persons are of entity type 'profile', remove inactive
  // persons from the list.
  foreach ($persons as $person_id => $person) {
    if ($person instanceof ProfileInterface && !$person->isPublished()) {
      unset($persons[$person_id]);
    }
  }
}

/*******************************************************************************
 * FORM ALTERS
 ******************************************************************************/

/**
 * Implements hook_form_FORM_ID_alter() for form 'commerce_order_event_edit_form'.
 *
 * @todo update
 */
function commerce_rng_form_commerce_order_event_edit_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
  $order = \Drupal::routeMatch()->getParameter('commerce_order');

  /* @var \Drupal\commerce_rng\RegistrationData $order_services */
  $order_services = \Drupal::service('commerce_rng.registration_data');

  // Create registrations for order items that don't have them yet.
  $order_services->generateOrderRegistrations($order);

  // Set up the registration output.
  $registrations = $order_services->getOrderRegistrations($order);
  $registrant_data = $order_services->formatRegistrationData($registrations);
  $buffer = [];

  foreach ($registrant_data as $registrant) {
    $product_variation_id = $registrant['product_variation_id'];
    if (!isset($buffer[$product_variation_id])) {
      $buffer[$product_variation_id] = commerce_rng_form_commerce_order_create_registration_form_container($order, $registrant['registration_id'], $registrant['product_variation_title']);
    }

    $edit_link = Link::fromTextAndUrl('edit',
      Url::fromRoute('commerce_rng.registrant_form.edit', [
        'commerce_order'      => $order->id(),
        'registrant'          => $registrant['registrant_id'],
      ]))->toString();

    $delete_link = Link::fromTextAndUrl('delete',
      Url::fromRoute('commerce_rng.registrant_form.delete', [
        'commerce_order'      => $order->id(),
        'registrant'          => $registrant['registrant_id'],
      ]))->toString();

    $buffer[$product_variation_id]['registrants'][] = [
      '#type' => 'item',
      '#markup' => t('@label (@edit | @delete)', [
        '@label' => $registrant['registrant_label'],
        '@edit' => $edit_link,
        '@delete' => $delete_link,
      ]),
    ];

  }

  // Add registrant links for registrations that don't have registrants yet.
  foreach ($registrations as $registration) {
    $order_item = $order_services->registrationGetOrderItem($registration);
    if ($order_item) {
      $product_variation = $order_item->getPurchasedEntity();
      if (!isset($buffer[$product_variation->id()])) {
        $buffer[$product_variation->id()] = commerce_rng_form_commerce_order_create_registration_form_container($order, $registration->id(), $product_variation->label());
      }
    }
  }

  if (!empty($buffer)) {
    $form['registrations-wrapper'] = [
      '#type' => 'details',
      '#title' => t('Registration Details'),
      '#group' => 'advanced',
      '#open' => TRUE,
      '#attributes' => [
        'class' => ['order-form-registrations'],
      ],
      '#weight' => 93,
    ];

    $form['registrations-wrapper']['registrations'] = $buffer;
  }
}

/**
 * Creates a registration form container.
 */
function commerce_rng_form_commerce_order_create_registration_form_container(OrderInterface $order, $registration_id, $product_variation_title) {
  $wrapper = [
    '#type' => 'container',
    '#attributes' => ['class' => ['product-variation']],
  ];

  $wrapper = [
    '#prefix' => '<div class="product-variation">',
    '#suffix' => '</div>',
  ];

  $wrapper['title'] = [
    '#markup' => '<h4 class="label">' . $product_variation_title . '</h4>',
  ];

  $create_link = Link::fromTextAndUrl('add registrant',
    Url::fromRoute('commerce_rng.registrant_form.add', [
      'commerce_order' => $order->id(),
      'registration' => $registration_id,
    ]))->toString();
  $wrapper['add_link'] = [
    '#markup' => $create_link,
    '#prefix' => '<div class="clearfix">',
    '#suffix' => '</div>',
  ];

  return $wrapper;
}

/*******************************************************************************
 * THEMING
 ******************************************************************************/

/**
 * Implements hook_preprocess_THEME_HOOK() for theme hook 'commerce_checkout_order_summary'.
 *
 * Adds registrants info order item extra data.
 */
function commerce_rng_preprocess_commerce_checkout_order_summary(&$variables) {
  if ($variables['checkout_step'] == 'review') {
    // Don't add registrants information on review step.
    return;
  }

  /** @var \Drupal\commerce_rng\RegistrationDataInterface $registration_data */
  $registration_data = \Drupal::service('commerce_rng.registration_data');

  $variables['order_item_extra'] = $registration_data->buildRegistrantLists($variables['order_entity']);
}

/**
 * Implements hook_preprocess_THEME_HOOK() for theme hook 'commerce_order_receipt'.
 */
function commerce_rng_preprocess_commerce_order_receipt(&$variables) {
  /** @var \Drupal\commerce_rng\RegistrationDataInterface $registration_data */
  $registration_data = \Drupal::service('commerce_rng.registration_data');

  $variables['order_item_extra'] = $registration_data->buildRegistrantLists($variables['order_entity']);
}
