<?php

/**
 * @file
 * An implementation of integration between RNG and Commerce.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\commerce_order\Entity\OrderInterface;
use Drupal\commerce_order\Entity\OrderItemInterface;
use Drupal\profile\Entity\ProfileInterface;
use Drupal\rng\Entity\RegistrantInterface;
use Drupal\rng\Entity\RegistrationInterface;

/*******************************************************************************
 * DRUPAL HOOKS.
 ******************************************************************************/

/**
 * Implements hook_entity_extra_field_info().
 */
function commerce_rng_entity_extra_field_info() {
  $extra = [];

  $extra['registrant']['registrant']['display']['registration'] = [
    'label' => t('Registration'),
    'description' => t('Link to the registration entity.'),
    'visible' => FALSE,
  ];
  $extra['registrant']['registrant']['display']['order'] = [
    'label' => t('Order', [], ['context' => 'commerce_order']),
    'description' => t('Link to the order that this registrant belongs to.'),
    'visible' => FALSE,
  ];
  $extra['registrant']['registrant']['display']['event'] = [
    'label' => t('Event'),
    'description' => t('Link to the event.'),
    'visible' => FALSE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view() for registrant entities.
 */
function commerce_rng_registrant_view(array &$build, RegistrantInterface $registrant, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('registration')) {
    $registration = $registrant->getRegistration();
    if ($registration instanceof RegistrationInterface && $registration->access('view')) {
      $build['registration'] = $registration->toLink(t('Registration'))->toRenderable();
    }
  }

  if ($display->getComponent('order')) {
    $registration = $registrant->getRegistration();
    if ($registration instanceof RegistrationInterface) {
      $order_item = \Drupal::service('commerce_rng.registration_data')
        ->registrationGetOrderItem($registration);
      if ($order_item instanceof OrderItemInterface) {
        $order = $order_item->getOrder();

        if ($order->access('view')) {
          $build['order'] = [
            '#type' => 'item',
            '#title' => t('Order', [], ['context' => 'commerce_order']),
            $order->toLink()->toRenderable(),
          ];
        }
      }
    }
  }

  if ($display->getComponent('event')) {
    $registration = $registrant->getRegistration();
    $event = $registration instanceof RegistrationInterface ? $registration->getEvent() : NULL;

    if ($event instanceof EntityInterface && $event->access('view')) {
      $build['event'] = [
        '#type' => 'item',
        '#title' => t('Event'),
        $event->toLink()->toRenderable(),
      ];
    }
  }
}

/*******************************************************************************
 * ENTITY HOOKS.
 ******************************************************************************/

/**
 * Implements hook_ENTITY_TYPE_presave() for entity type 'commerce_order_item'.
 */
function commerce_rng_commerce_order_item_presave(OrderItemInterface $order_item) {
  // Update the order item's quantity.
  \Drupal::service('commerce_rng.registration_data')->orderItemUpdateQuantity($order_item);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for entity type 'commerce_order_item'.
 */
function commerce_rng_commerce_order_item_delete(OrderItemInterface $order_item) {
  // Cleanup registration when order item gets deleted.
  $registration = \Drupal::service('commerce_rng.registration_data')->getRegistrationByOrderItemId($order_item->id());
  if ($registration instanceof RegistrationInterface) {
    $registration->delete();
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for entity type 'registrant'.
 */
function commerce_rng_registrant_insert(RegistrantInterface $registrant) {
  $registration = $registrant->getRegistration();
  if (!$registration instanceof RegistrationInterface) {
    return;
  }

  $order_item = \Drupal::service('commerce_rng.registration_data')->registrationGetOrderItem($registration);
  if (!$order_item instanceof OrderItemInterface) {
    return;
  }

  // Update the order item.
  $order_item->save();
}

/**
 * Implements hook_ENTITY_TYPE_update() for entity type 'registrant'.
 */
function commerce_rng_registrant_update(RegistrantInterface $registrant) {
  // Do the same as when inserting a registrant.
  commerce_rng_registrant_insert($registrant);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for entity type 'registrant'.
 */
function commerce_rng_registrant_delete(RegistrantInterface $registrant) {
  // Do the same as when inserting a registrant.
  commerce_rng_registrant_insert($registrant);
}

/*******************************************************************************
 * COMMERCE RNG HOOKS.
 ******************************************************************************/

/**
 * Implements hook_commerce_rng_persons_list_alter().
 */
function commerce_rng_commerce_rng_persons_list_alter(array &$persons, OrderInterface $order, RegistrationInterface $registration) {
  // If the list of persons are of entity type 'profile', remove inactive
  // persons from the list.
  foreach ($persons as $person_id => $person) {
    if ($person instanceof ProfileInterface && !$person->isPublished()) {
      unset($persons[$person_id]);
    }
  }
}

/*******************************************************************************
 * FORM ALTERS.
 ******************************************************************************/

/**
 * Implements hook_form_FORM_ID_alter() for form 'commerce_order_event_edit_form'.
 *
 * @todo update
 */
function commerce_rng_form_commerce_order_event_edit_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
  $order = \Drupal::routeMatch()->getParameter('commerce_order');

  /** @var \Drupal\commerce_rng\RegistrationData $order_services */
  $order_services = \Drupal::service('commerce_rng.registration_data');

  // Create registrations for order items that don't have them yet.
  $order_services->generateOrderRegistrations($order);

  // Set up the registration output.
  $registrations = $order_services->getOrderRegistrations($order);
  $registrant_data = $order_services->formatRegistrationData($registrations);
  $buffer = [];

  foreach ($registrant_data as $registrant) {
    $product_variation_id = $registrant['product_variation_id'];
    if (!isset($buffer[$product_variation_id])) {
      $buffer[$product_variation_id] = commerce_rng_form_commerce_order_create_registration_form_container($order, $registrant['registration_id'], $registrant['product_variation_title']);

      $buffer[$product_variation_id]['registrants'] = [
        '#theme' => 'table',
        '#header' => [
          'label' => t('Name'),
          'actions' => t('Operations'),
        ],
        '#rows' => [],
      ];
    }

    $buffer[$product_variation_id]['registrants']['#rows'][] = [
      'label' => $registrant['registrant_label'],
      'actions' => [
        'data' => [
          '#type' => 'inline_template',
          '#template' => '{{ edit }} {{ delete }}',
          '#context' => [
            'edit' => [
              '#type' => 'link',
              '#title' => t('Edit'),
              '#url' => Url::fromRoute('commerce_rng.registrant_form.edit', [
                'commerce_order' => $order->id(),
                'registrant' => $registrant['registrant_id'],
              ]),
              '#attributes' => [
                'class' => 'button',
              ],
            ],
            'delete' => [
              '#type' => 'link',
              '#title' => t('Delete'),
              '#url' => Url::fromRoute('commerce_rng.registrant_form.delete', [
                'commerce_order' => $order->id(),
                'registrant' => $registrant['registrant_id'],
              ]),
              '#attributes' => [
                'class' => 'button',
              ],
            ],
          ],
        ],
      ],
    ];
  }

  // Add registrant links for registrations that don't have registrants yet.
  foreach ($registrations as $registration) {
    $order_item = $order_services->registrationGetOrderItem($registration);
    if ($order_item instanceof OrderItemInterface) {
      $product_variation = $order_item->getPurchasedEntity();
      if (!isset($buffer[$product_variation->id()])) {
        $buffer[$product_variation->id()] = commerce_rng_form_commerce_order_create_registration_form_container($order, $registration->id(), $product_variation->label());
      }
    }
  }

  if (!empty($buffer)) {
    // Display underneath order_items.
    if (isset($form['order_items']['#weight'])) {
      $weight = $form['order_items']['#weight'] + 1;
    }
    else {
      $weight = 1;
    }
    $form['registrations-wrapper'] = [
      '#type' => 'fieldset',
      '#title' => t('Registration details'),
      '#attributes' => [
        'class' => ['order-form-registrations'],
      ],
      '#weight' => $weight,
    ];

    $form['registrations-wrapper']['registrations'] = $buffer;
  }
}

/**
 * Creates a registration form container.
 */
function commerce_rng_form_commerce_order_create_registration_form_container(OrderInterface $order, $registration_id, $product_variation_title) {
  $wrapper = [
    '#type' => 'container',
    '#attributes' => ['class' => ['product-variation']],
  ];

  $wrapper = [
    '#prefix' => '<div class="product-variation">',
    '#suffix' => '</div>',
  ];

  $wrapper['title'] = [
    '#markup' => '<h4 class="label">' . $product_variation_title . '</h4>',
  ];

  $wrapper['add_link'] = [
    '#type' => 'link',
    '#title' => t('Add registrant'),
    '#url' => Url::fromRoute('commerce_rng.registrant_form.add', [
      'commerce_order' => $order->id(),
      'registration' => $registration_id,
    ]),
    '#attributes' => [
      'class' => 'button',
    ],
  ];

  return $wrapper;
}

/*******************************************************************************
 * THEMING.
 ******************************************************************************/

/**
 * Implements hook_preprocess_THEME_HOOK() for theme hook 'commerce_checkout_order_summary'.
 *
 * Adds registrants info order item extra data.
 */
function commerce_rng_preprocess_commerce_checkout_order_summary(&$variables) {
  if ($variables['checkout_step'] == 'review') {
    // Don't add registrants information on review step.
    return;
  }

  /** @var \Drupal\commerce_rng\RegistrationDataInterface $registration_data */
  $registration_data = \Drupal::service('commerce_rng.registration_data');

  $variables['order_item_extra'] = $registration_data->buildRegistrantLists($variables['order_entity']);
}

/**
 * Implements hook_preprocess_THEME_HOOK() for theme hook 'commerce_order_receipt'.
 */
function commerce_rng_preprocess_commerce_order_receipt(&$variables) {
  /** @var \Drupal\commerce_rng\RegistrationDataInterface $registration_data */
  $registration_data = \Drupal::service('commerce_rng.registration_data');

  $variables['order_item_extra'] = $registration_data->buildRegistrantLists($variables['order_entity']);
}
